// Generated by CoffeeScript 1.8.0
(function() {
  var flip, map, style;

  mapboxgl.accessToken = 'pk.eyJ1Ijoic3RlcmxpbmdyYWRjbGlmZiIsImEiOiIxYlFFV19rIn0.6AHWkJQtrDolNlMjguMmCQ';

  style = 'satellite';

  flip = function() {
    if (style === 'satellite') {
      mapboxgl.util.getJSON('https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v6.json', function(err, style) {
        return map.setStyle(style);
      });
      return style = 'outdoors';
    } else {
      mapboxgl.util.getJSON('https://www.mapbox.com/mapbox-gl-styles/styles/satellite-v6.json', function(err, style) {
        return map.setStyle(style);
      });
      return style = 'satellite';
    }
  };

  if (!mapboxgl.util.supported()) {
    alert('Your browser does not support Mapbox GL');
  } else {
    map = new mapboxgl.Map({
      container: 'map',
      style: 'https://www.mapbox.com/mapbox-gl-styles/styles/satellite-v6.json',
      center: [32.98754, -117.04367],
      zoom: 13
    });
    map.addControl(new mapboxgl.Navigation());
  }

  $('#button').click(flip);

}).call(this);
